services:
  app:
    container_name: qyg-api
    image: qyg-api:0.1.0
    restart: always
    env_file:
      - .env
    ports:
      - 8002:8000
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    command: ["./.venv/bin/uvicorn", "app.main:app", "--host", "::", "--port", "8000"]
